# Segmenting and Clustering Neighborhoods in Toronto

In [2]:
# importing the library
import pandas as pd

# reading the table from html page
borough = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]

In [3]:
#reading the head of the dataframe
borough.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

#### Removing the Boroughs which are having value as Not assigned

In [4]:
indexnames = borough[borough['Borough'] == 'Not assigned'].index

borough.drop(indexnames,inplace = True)

In [5]:
# head of the dataframe
borough.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights

#### More than one neighborhood can exist in one postal code area. So,Those two rows will be combined into one row with the neighborhoods separated with a comma

In [6]:
borough = borough.groupby('Postcode').agg({'Borough':'first', 
                             'Neighbourhood': ', '.join}).reset_index()

In [7]:
borough.head()

  Postcode      Borough                           Neighbourhood
0      M1B  Scarborough                          Rouge, Malvern
1      M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2      M1E  Scarborough       Guildwood, Morningside, West Hill
3      M1G  Scarborough                                  Woburn
4      M1H  Scarborough                               Cedarbrae

#### For Borough's  having Neighbourhood as "Not assigned" , Assigning the Neighbourhood with the same name as Borough's name

In [8]:
# replacing the value of neighbourhood with borough name
borough.Neighbourhood.replace('Not assigned',borough.Borough,inplace=True)

In [9]:
borough

,Postcode,Borough,Neighbourhood
0,M1B,Scarborough,"Rouge, Malvern"
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park"
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge"
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff, Cliffside West"
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ..."
11,M1R,Scarborough,"Maryvale, Wexford"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter"
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St..."
15,M1W,Scarborough,L'Amoreaux West
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview, Henry Farm, Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"Silver Hills, York Mills"
21,M2M,North York,"Newtonbrook, Willowdale"
22,M2N,North York,Willowdale South
23,M2P,North York,York Mills West
24,M2R,North York,Willowdale West
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills North
27,M3C,North York,"Flemingdon Park, Don Mills South"
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights"
29,M3J,North York,"Northwood Park, York University"
...,...,...,...
73,M6C,York,Humewood-Cedarvale
74,M6E,York,Caledonia-Fairbanks
75,M6G,Downtown Toronto,Christie
76,M6H,West Toronto,"Dovercourt Village, Dufferin"
77,M6J,West Toronto,"Little Portugal, Trinity"
78,M6K,West Toronto,"Brockton, Exhibition Place, Parkdale Village"
79,M6L,North York,"Downsview, North Park, Upwood Park"
80,M6M,York,"Del Ray, Keelesdale, Mount Dennis, Silverthorn"
81,M6N,York,"The Junction North, Runnymede"
82,M6P,West Toronto,"High Park, The Junction South"
83,M6R,West Toronto,"Parkdale, Roncesvalles"
84,M6S,West Toronto,"Runnymede, Swansea"
85,M7A,Queen's Park,Queen's Park
86,M7R,Mississauga,Canada Post Gateway Processing Centre
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto"
89,M8W,Etobicoke,"Alderwood, Long Branch"
90,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
91,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So..."
92,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen..."
93,M9A,Etobicoke,Islington Avenue
94,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."
95,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol..."
96,M9L,North York,Humber Summit
97,M9M,North York,"Emery, Humberlea"
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv..."
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ..."
102,M9W,Etobicoke,Northwest

In [10]:
# shape of the dataframe
borough.shape

(103, 3)

In [11]:
location = pd.read_csv('Desktop/Geospatial_Coordinates.csv')

In [12]:
location.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [13]:
location = location.drop('Postal Code',1)

In [14]:
location.head()

    Latitude  Longitude
0  43.806686 -79.194353
1  43.784535 -79.160497
2  43.763573 -79.188711
3  43.770992 -79.216917
4  43.773136 -79.239476

In [15]:
data = pd.concat([borough,location],axis = 1)

In [16]:
data

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St...",43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,43.803762,-79.363452
18,M2J,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
19,M2K,North York,Bayview Village,43.786947,-79.385975
20,M2L,North York,"Silver Hills, York Mills",43.757490,-79.374714
21,M2M,North York,"Newtonbrook, Willowdale",43.789053,-79.408493
22,M2N,North York,Willowdale South,43.770120,-79.408493
23,M2P,North York,York Mills West,43.752758,-79.400049
24,M2R,North York,Willowdale West,43.782736,-79.442259
25,M3A,North York,Parkwoods,43.753259,-79.329656
26,M3B,North York,Don Mills North,43.745906,-79.352188
27,M3C,North York,"Flemingdon Park, Don Mills South",43.725900,-79.340923
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights",43.754328,-79.442259
29,M3J,North York,"Northwood Park, York University",43.767980,-79.487262
...,...,...,...,...,...
73,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
74,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512
75,M6G,Downtown Toronto,Christie,43.669542,-79.422564
76,M6H,West Toronto,"Dovercourt Village, Dufferin",43.669005,-79.442259
77,M6J,West Toronto,"Little Portugal, Trinity",43.647927,-79.419750
78,M6K,West Toronto,"Brockton, Exhibition Place, Parkdale Village",43.636847,-79.428191
79,M6L,North York,"Downsview, North Park, Upwood Park",43.713756,-79.490074
80,M6M,York,"Del Ray, Keelesdale, Mount Dennis, Silverthorn",43.691116,-79.476013
81,M6N,York,"The Junction North, Runnymede",43.673185,-79.487262
82,M6P,West Toronto,"High Park, The Junction South",43.661608,-79.464763
83,M6R,West Toronto,"Parkdale, Roncesvalles",43.648960,-79.456325
84,M6S,West Toronto,"Runnymede, Swansea",43.651571,-79.484450
85,M7A,Queen's Park,Queen's Park,43.662301,-79.389494
86,M7R,Mississauga,Canada Post Gateway Processing Centre,43.636966,-79.615819
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,43.662744,-79.321558
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto",43.605647,-79.501321
89,M8W,Etobicoke,"Alderwood, Long Branch",43.602414,-79.543484
90,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
91,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So...",43.636258,-79.498509
92,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen...",43.628841,-79.520999
93,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
94,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ...",43.650943,-79.554724
95,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol...",43.643515,-79.577201
96,M9L,North York,Humber Summit,43.756303,-79.565963
97,M9M,North York,"Emery, Humberlea",43.724766,-79.532242
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv...",43.688905,-79.554724
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054

### Segmentation and clustering

In [17]:
import folium

In [18]:
from geopy.geocoders import Nominatim

In [19]:
### getting the cordinates of Toronto
address = 'Toronto, ON,Canada'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of New York City are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of New York City are 43.653963, -79.387207.

#### Create a map of Toronto with neighborhoods superimposed on top

In [24]:
# create map of New York using latitude and longitude values
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=10)


    
map_toronto

In [21]:
CLIENT_ID = '4GE5AJ2TZ1XOC3V1PJZL1JULZGGGLFS0T5GNOCMI0UJ5OMAB' # your Foursquare ID
CLIENT_SECRET = '2FVHGA44OEZDSIQALXVW20QHES13DHYZBSOQ5SRNI2L2FEO1' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 4GE5AJ2TZ1XOC3V1PJZL1JULZGGGLFS0T5GNOCMI0UJ5OMAB
CLIENT_SECRET:2FVHGA44OEZDSIQALXVW20QHES13DHYZBSOQ5SRNI2L2FEO1

In [26]:
downtown_toronto_borough = data[data['Borough'].str.contains("Downtown Toronto")]

In [27]:
downtown_toronto_borough.reset_index()

,index,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,50,M4W,Downtown Toronto,Rosedale,43.679563,-79.377529
1,51,M4X,Downtown Toronto,"Cabbagetown, St. James Town",43.667967,-79.367675
2,52,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
3,53,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.654260,-79.360636
4,54,M5B,Downtown Toronto,"Ryerson, Garden District",43.657162,-79.378937
5,55,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
6,56,M5E,Downtown Toronto,Berczy Park,43.644771,-79.373306
7,57,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
8,58,M5H,Downtown Toronto,"Adelaide, King, Richmond",43.650571,-79.384568
9,59,M5J,Downtown Toronto,"Harbourfront East, Toronto Islands, Union Station",43.640816,-79.381752
10,60,M5K,Downtown Toronto,"Design Exchange, Toronto Dominion Centre",43.647177,-79.381576
11,61,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel",43.648198,-79.379817
12,66,M5S,Downtown Toronto,"Harbord, University of Toronto",43.662696,-79.400049
13,67,M5T,Downtown Toronto,"Chinatown, Grange Park, Kensington Market",43.653206,-79.400049
14,68,M5V,Downtown Toronto,"CN Tower, Bathurst Quay, Island airport, Harbo...",43.628947,-79.394420
15,69,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade,43.646435,-79.374846
16,70,M5X,Downtown Toronto,"First Canadian Place, Underground city",43.648429,-79.382280
17,75,M6G,Downtown Toronto,Christie,43.669542,-79.422564

#### Let's explore the first neighborhood in our dataframe.

In [33]:
downtown_toronto_borough.iloc[0,2]

'Rosedale'

In [34]:
neighborhood_latitude = downtown_toronto_borough.iloc[0, 3] # neighborhood latitude value
neighborhood_longitude = downtown_toronto_borough.iloc[0, 4] # neighborhood longitude value

neighborhood_name = downtown_toronto_borough.iloc[0,2] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               neighborhood_latitude, 
                                                               neighborhood_longitude))

Latitude and longitude values of Rosedale are 43.6795626, -79.37752940000001.

In [35]:
# type your answer here
LIMIT = 100
radius = 500

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)


    
url

'https://api.foursquare.com/v2/venues/explore?&client_id=4GE5AJ2TZ1XOC3V1PJZL1JULZGGGLFS0T5GNOCMI0UJ5OMAB&client_secret=2FVHGA44OEZDSIQALXVW20QHES13DHYZBSOQ5SRNI2L2FEO1&v=20180605&ll=43.6795626,-79.37752940000001&radius=500&limit=100'

In [37]:
import json
import requests
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5cf4d8006a6071493b2ca416'},
 'response': {'headerLocation': 'Rosedale',
  'headerFullLocation': 'Rosedale, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 4,
  'suggestedBounds': {'ne': {'lat': 43.6840626045, 'lng': -79.37131878274371},
   'sw': {'lat': 43.675062595499995, 'lng': -79.38374001725632}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4aff2d47f964a520743522e3',
       'name': 'Rosedale Park',
       'location': {'address': '38 Scholfield Ave.',
        'crossStreet': 'at Edgar Ave.',
        'lat': 43.68232820227814,
        'lng': -79.37893434347683,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.68232820227814,
          'lng': -79.37893434347683}],
        'distance': 327,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['38 Scholfield Ave. (at Edgar Ave.)',
         'Toronto ON',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d1e7941735',
         'name': 'Playground',
         'pluralName': 'Playgrounds',
         'shortName': 'Playground',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/playground_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4aff2d47f964a520743522e3-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4bd777aa5cf276b054639b00',
       'name': 'Whitney Park',
       'location': {'lat': 43.68203573063681,
        'lng': -79.37378835021306,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.68203573063681,
          'lng': -79.37378835021306}],
        'distance': 408,
        'cc': 'CA',
        'country': 'Canada',
        'formattedAddress': ['Canada']},
       'categories': [{'id': '4bf58dd8d48988d163941735',
         'name': 'Park',
         'pluralName': 'Parks',
         'shortName': 'Park',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4bd777aa5cf276b054639b00-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4d0e77df76cc37045715767c',
       'name': 'Alex Murray Parkette',
       'location': {'address': '107 Crescent Road',
        'crossStreet': 'South Drive',
        'lat': 43.678300240478954,
        'lng': -79.38277328698108,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.678300240478954,
          'lng': -79.38277328698108}],
        'distance': 444,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['107 Crescent Road (South Drive)',
         'Toronto ON',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d163941735',
         'name': 'Park',
         'pluralName': 'Parks',
         'shortName': 'Park',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4d0e77df76cc37045715767c-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ef8f2a3775b54cdb5bdec7c',
       'name': "Milkman's Lane",
       'location': {'address': 'South Dr',
        'crossStreet': 'at Glen Rd',
        'lat': 43.676352068015554,
        'lng': -79.37384239440172,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.676352068015554,
          'lng': -79.37384239440172}],
        'distance': 464,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['South Dr (at Glen Rd)', 'Toronto ON', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d159941735',
         'name': 'Trail',
         'pluralName': 'Trails',
         'shortName': 'Trail',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/hikingtrail_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4ef8f2a3775b54cdb5bdec7c-3'}]}]}}

In [38]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Now we are ready to clean the json and structure it into a pandas dataframe.

In [43]:
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

                   name  categories        lat        lng
0         Rosedale Park  Playground  43.682328 -79.378934
1          Whitney Park        Park  43.682036 -79.373788
2  Alex Murray Parkette        Park  43.678300 -79.382773
3        Milkman's Lane       Trail  43.676352 -79.373842

In [42]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

4 venues were returned by Foursquare.

### Explore Neighborhoods in downtown toronto

In [44]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [46]:
downtown_toronto_venue = getNearbyVenues(names=downtown_toronto_borough['Neighbourhood'],
                                   latitudes=downtown_toronto_borough['Latitude'],
                                   longitudes=downtown_toronto_borough['Longitude']
                                  )

Rosedale
Cabbagetown, St. James Town
Church and Wellesley
Harbourfront, Regent Park
Ryerson, Garden District
St. James Town
Berczy Park
Central Bay Street
Adelaide, King, Richmond
Harbourfront East, Toronto Islands, Union Station
Design Exchange, Toronto Dominion Centre
Commerce Court, Victoria Hotel
Harbord, University of Toronto
Chinatown, Grange Park, Kensington Market
CN Tower, Bathurst Quay, Island airport, Harbourfront West, King and Spadina, Railway Lands, South Niagara
Stn A PO Boxes 25 The Esplanade
First Canadian Place, Underground city
Christie

In [47]:
print(downtown_toronto_venue.shape)
downtown_toronto_venue.head()

(1284, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Rosedale,43.679563,-79.377529,Rosedale Park,43.682328,-79.378934,Playground
1,Rosedale,43.679563,-79.377529,Whitney Park,43.682036,-79.373788,Park
2,Rosedale,43.679563,-79.377529,Alex Murray Parkette,43.678300,-79.382773,Park
3,Rosedale,43.679563,-79.377529,Milkman's Lane,43.676352,-79.373842,Trail
4,"Cabbagetown, St. James Town",43.667967,-79.367675,Cranberries,43.667843,-79.369407,Diner

Let's check how many venues were returned for each neighborhood

In [48]:
downtown_toronto_venue.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
"Adelaide, King, Richmond",100,100,100,100,100,100
Berczy Park,56,56,56,56,56,56
"CN Tower, Bathurst Quay, Island airport, Harbourfront West, King and Spadina, Railway Lands, South Niagara",15,15,15,15,15,15
"Cabbagetown, St. James Town",45,45,45,45,45,45
Central Bay Street,85,85,85,85,85,85
"Chinatown, Grange Park, Kensington Market",100,100,100,100,100,100
Christie,16,16,16,16,16,16
Church and Wellesley,87,87,87,87,87,87
"Commerce Court, Victoria Hotel",100,100,100,100,100,100
"Design Exchange, Toronto Dominion Centre",100,100,100,100,100,100
"First Canadian Place, Underground city",100,100,100,100,100,100
"Harbord, University of Toronto",35,35,35,35,35,35
"Harbourfront East, Toronto Islands, Union Station",100,100,100,100,100,100
"Harbourfront, Regent Park",47,47,47,47,47,47
Rosedale,4,4,4,4,4,4
"Ryerson, Garden District",100,100,100,100,100,100
St. James Town,100,100,100,100,100,100
Stn A PO Boxes 25 The Esplanade,94,94,94,94,94,94

In [49]:
print('There are {} uniques categories.'.format(len(downtown_toronto_venue['Venue Category'].unique())))

There are 209 uniques categories.

#### Analyze each neighbourhood

In [52]:
# one hot encoding
downtown_toronto_onehot = pd.get_dummies(downtown_toronto_venue[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
downtown_toronto_onehot['Neighborhood'] = downtown_toronto_venue['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [downtown_toronto_onehot.columns[-1]] + list(downtown_toronto_onehot.columns[:-1])
downtown_toronto_onehot = downtown_toronto_onehot[fixed_columns]

downtown_toronto_onehot.head()

,Yoga Studio,Adult Boutique,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,...,Thrift / Vintage Store,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Wings Joint,Women's Store
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
downtown_toronto_onehot.shape

(1284, 209)

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [54]:
downtown_grouped = downtown_toronto_onehot.groupby('Neighborhood').mean().reset_index()
downtown_grouped

,Neighborhood,Yoga Studio,Adult Boutique,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,...,Thrift / Vintage Store,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Wings Joint,Women's Store
0,"Adelaide, King, Richmond",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.000000,0.010000,0.000000,0.00
1,Berczy Park,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.017857,0.000000,0.000000,0.000000,0.000000,0.00
2,"CN Tower, Bathurst Quay, Island airport, Harbo...",0.000000,0.000000,0.000000,0.066667,0.066667,0.066667,0.133333,0.2,0.133333,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
3,"Cabbagetown, St. James Town",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
4,Central Bay Street,0.011765,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.011765,0.000000,0.000000,0.011765,0.000000,0.00
5,"Chinatown, Grange Park, Kensington Market",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.01,0.01,0.00,0.00,0.060000,0.000000,0.030000,0.010000,0.000000,0.00
6,Christie,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
7,Church and Wellesley,0.011494,0.011494,0.011494,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.000000,0.011494,0.011494,0.000000,0.011494,0.00
8,"Commerce Court, Victoria Hotel",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.000000,0.010000,0.000000,0.00
9,"Design Exchange, Toronto Dominion Centre",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.01,0.010000,0.000000,0.000000,0.010000,0.000000,0.00
10,"First Canadian Place, Underground city",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.01,0.010000,0.000000,0.000000,0.010000,0.000000,0.00
11,"Harbord, University of Toronto",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.000000,0.028571,0.000000,0.000000,0.000000,0.00
12,"Harbourfront East, Toronto Islands, Union Station",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.01,0.010000,0.000000,0.000000,0.010000,0.000000,0.00
13,"Harbourfront, Regent Park",0.021277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
14,Rosedale,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.25,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
15,"Ryerson, Garden District",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.01,0.00,0.00,0.010000,0.010000,0.010000,0.010000,0.000000,0.00
16,St. James Town,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.000000,0.000000,0.000000,0.01
17,Stn A PO Boxes 25 The Esplanade,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00,0.00,0.00,0.00,0.010638,0.000000,0.000000,0.000000,0.000000,0.00

In [55]:
num_top_venues = 5

for hood in downtown_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = downtown_grouped[downtown_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Adelaide, King, Richmond----
                 venue  freq
0          Coffee Shop  0.06
1                 Café  0.05
2           Steakhouse  0.04
3  American Restaurant  0.04
4                  Bar  0.04


----Berczy Park----
          venue  freq
0   Coffee Shop  0.09
1  Cocktail Bar  0.05
2    Restaurant  0.04
3          Café  0.04
4        Bakery  0.04


----CN Tower, Bathurst Quay, Island airport, Harbourfront West, King and Spadina, Railway Lands, South Niagara----
              venue  freq
0   Airport Service  0.20
1  Airport Terminal  0.13
2    Airport Lounge  0.13
3   Harbor / Marina  0.07
4  Sculpture Garden  0.07


----Cabbagetown, St. James Town----
                venue  freq
0         Coffee Shop  0.09
1                Park  0.04
2  Italian Restaurant  0.04
3                 Pub  0.04
4          Restaurant  0.04


----Central Bay Street----
                venue  freq
0         Coffee Shop  0.16
1                Café  0.05
2  Italian Restaurant  0.05
3        Burger Joint  0.04
4      Sandwich Place  0.04


----Chinatown, Grange Park, Kensington Market----
                           venue  freq
0                           Café  0.08
1  Vegetarian / Vegan Restaurant  0.06
2             Mexican Restaurant  0.04
3            Dumpling Restaurant  0.04
4                    Coffee Shop  0.04


----Christie----
               venue  freq
0               Café  0.19
1      Grocery Store  0.19
2               Park  0.12
3              Diner  0.06
4  Convenience Store  0.06


----Church and Wellesley----
                 venue  freq
0          Coffee Shop  0.07
1  Japanese Restaurant  0.07
2     Sushi Restaurant  0.06
3              Gay Bar  0.03
4           Restaurant  0.03


----Commerce Court, Victoria Hotel----
                 venue  freq
0          Coffee Shop  0.11
1                 Café  0.07
2                Hotel  0.06
3           Restaurant  0.05
4  American Restaurant  0.04


----Design Exchange, Toronto Dominion Centre----
         venue  freq
0  Coffee Shop  0.12
1         Café  0.07
2        Hotel  0.07
3   Restaurant  0.05
4    Gastropub  0.03


----First Canadian Place, Underground city----
          venue  freq
0          Café  0.09
1   Coffee Shop  0.09
2         Hotel  0.04
3  Burger Joint  0.03
4    Restaurant  0.03


----Harbord, University of Toronto----
                 venue  freq
0                 Café  0.11
1            Bookstore  0.09
2           Restaurant  0.06
3  Japanese Restaurant  0.06
4               Bakery  0.06


----Harbourfront East, Toronto Islands, Union Station----
                venue  freq
0         Coffee Shop  0.12
1            Aquarium  0.05
2               Hotel  0.05
3                Café  0.04
4  Italian Restaurant  0.04


----Harbourfront, Regent Park----
         venue  freq
0  Coffee Shop  0.15
1       Bakery  0.06
2         Park  0.06
3          Pub  0.06
4      Theater  0.04


----Rosedale----
         venue  freq
0         Park  0.50
1   Playground  0.25
2        Trail  0.25
3  Yoga Studio  0.00
4       Museum  0.00


----Ryerson, Garden District----
                       venue  freq
0                Coffee Shop  0.10
1             Clothing Store  0.06
2             Cosmetics Shop  0.04
3                       Café  0.04
4  Middle Eastern Restaurant  0.03


----St. James Town----
            venue  freq
0     Coffee Shop  0.07
1            Café  0.06
2      Restaurant  0.05
3           Hotel  0.05
4  Cosmetics Shop  0.04


----Stn A PO Boxes 25 The Esplanade----
                venue  freq
0         Coffee Shop  0.11
1          Restaurant  0.04
2                Café  0.04
3  Italian Restaurant  0.03
4        Cocktail Bar  0.03

### Putting it into a dataframe

In [56]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [58]:
import numpy as np
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = downtown_grouped['Neighborhood']

for ind in np.arange(downtown_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(downtown_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Adelaide, King, Richmond",Coffee Shop,Café,Bar,American Restaurant,Thai Restaurant,Steakhouse,Bakery,Hotel,Burger Joint,Cosmetics Shop
1,Berczy Park,Coffee Shop,Cocktail Bar,Beer Bar,Bakery,Farmers Market,Seafood Restaurant,Steakhouse,Cheese Shop,Café,Restaurant
2,"CN Tower, Bathurst Quay, Island airport, Harbo...",Airport Service,Airport Lounge,Airport Terminal,Boutique,Harbor / Marina,Sculpture Garden,Airport,Airport Food Court,Airport Gate,Boat or Ferry
3,"Cabbagetown, St. James Town",Coffee Shop,Italian Restaurant,Pub,Restaurant,Pizza Place,Café,Park,Bakery,Chinese Restaurant,Pet Store
4,Central Bay Street,Coffee Shop,Italian Restaurant,Café,Sandwich Place,Burger Joint,Spa,Indian Restaurant,Japanese Restaurant,Sushi Restaurant,Middle Eastern Restaurant

In [59]:
# import k-means from clustering stage
from sklearn.cluster import KMeans

### Cluster Neighborhoods

In [60]:
# set number of clusters
kclusters = 5

downtown_grouped_clustering = downtown_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(downtown_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 0, 4, 0, 0, 3, 2, 0, 0, 0])